---
asdf_install: true
asdf_version: 0.9.0
asdf_user: "{{ lookup('env', 'USER') }}"
asdf_home: "{{ lookup('env', 'HOME') }}"
# asdf_sha256 : the checksum on the source for the release in GitHub. Required
# by the asdf role used for Linux distros. Not required for the macOS role.
asdf_sha256: >
  f2ab54bf1d17e10f17e405c2fac29f0620a66b5c7a5200b5699e50e28ed210c8
asdf_plugins:
  - name: nodejs
    versions: ["14.17.6", "16.13.2"]
    global: "16.13.2"
