---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
      ansible_sudo_pass: "${ANSIBLE_SUDO_PASSWORD}"
  become_method: sudo
lint: |
  set -e
  yamllint .
  ansible-lint --exclude ${HOME}/.ansible/roles/ --exclude ${HOME}/.cache/
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: ansible
