dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint --exclude ${HOME}/.ansible/roles/ --exclude ${HOME}/.cache/
platforms:
  - name: instance
    # Must use the config below for ansible to work in the container.
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
