---
- name: Verify
  hosts: all
  gather_facts: true

  tasks:

    - name: Capture asdf --help response when interactive bash shell
      command: bash -i -c "asdf --help"
      register: asdf_help_output
      changed_when: false

    - name: Check that asdf works from interative bash shell
      assert:
        that: "'asdf plugin' in asdf_help_output.stdout"

    # Also wanted to check that one of the plugins we installed is working in
    # bash. Not to test that asdf plugins were installed, but that a dev could
    # actually use them from bash.
    - name: Capture node help response when interactive bash shell
      command: bash -i -c "node --help"
      register: node_help_output
      changed_when: false

    - name: Check that node works from interactive bash shell
      assert:
        that: "'Usage: node' in node_help_output.stdout"
