---
name: Ubuntu-CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Molecule
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        # If we want to test multiple operating systems, add to the list below.
        os: ["ubuntu-20.04"]
        python-version: [3.8.10]
        # if we want to test multiple scenarios, add to the list below.
        # NOTE - scenarios match the folder names in ./molecule by default.
        scenario: ["ubuntu", "ubuntu_no_asdf_install"]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker,lint] yamllint ansible-lint

      - name: Setup test environment.
        run: ansible-galaxy install -r requirements.yml

      - name: Run Molecule tests.
        run: molecule test -s "${SCENARIO}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          SCENARIO: ${{ matrix.scenario }}
